version: '3.1'

services:
  app:
    build:
      context: ./
    depends_on: 
      - db_demo
    ports:
      - 8088:8080
  db_demo:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro
    ports:
      - 3303:3306