CREATE DATABASE IF NOT EXISTS `management_student`;

USE `management_student`;

CREATE TABLE IF NOT EXISTS `student`(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(255) NOT NULL,
    `address` VARCHAR(255) NOT NULL,
    `phone_number` VARCHAR(255) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `status` INT NOT NULL
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS  `subject`(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `subject_name` VARCHAR(255) NOT NULL,
    `time` INT NOT NULL
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS  `result`(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `point` INT NOT NULL,
    `comment` VARCHAR(255) NOT NULL
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS `registration`(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `id_subject` INT UNSIGNED NOT NULL,
    `id_student` INT UNSIGNED NOT NULL,
    `id_result` INT UNSIGNED NOT NULL,
    FOREIGN KEY (id_subject) REFERENCES `subject` (id) ON DELETE CASCADE,
    FOREIGN KEY (id_student) REFERENCES `student` (id) ON DELETE CASCADE,
    FOREIGN KEY (id_result) REFERENCES `result` (id) ON DELETE CASCADE
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS  `class`(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `class_name` VARCHAR(255) NOT NULL,
    `id_student` INT UNSIGNED NOT NULL,
    FOREIGN KEY (id_student) REFERENCES `student` (id) ON DELETE CASCADE
) ENGINE=INNODB;

CREATE TABLE  IF NOT EXISTS `faculty`(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `faculty_name` VARCHAR(255) NOT NULL,
    `phone_number` VARCHAR(255) NOT NULL,
    `id_class` INT UNSIGNED NOT NULL,
    FOREIGN KEY (id_class) REFERENCES `class` (id) ON DELETE CASCADE
) ENGINE=INNODB;
